### ISSUE TITLE
migrate inko.js to inko.py

### ISSUE THREAD

**Issue by 738** [738/inko#9]
* migrate inko.js to inko.py
* https://github.com/jonjee/inko.py 레포지토리 생성함

**Comment by JackCme** [comment]
Hi 😊,
I made a [PR](https://github.com/738/inko.py/pull/1) for migration into python!
파이썬 구현 PR 했습니다!

**Comment by playBranden** [comment]
Python migration 완료했습니다
- [x] Write test code
- [x] Package module and release

**Comment by JackCme** [comment]
Python migration 완료되었습니다.
- [x] Write test code
- [x] Package module and release

**Comment by 738** [comment]
@JackCme 
수고하셨습니다! README에 관련 내용 추가했습니다.
